[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#007BFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#2C3E50"
font = "sans serif"

[browser]
gatherUsageStats = false